name: Build docker images
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Image
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build and push ARM platform
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/arm64
          build-args: |
            BASE_IMG=coolyzp/tinymediamanager-arm:latest
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tinymediamanager-arm:latest

      - name: Build and push AMD platform
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          build-args: |
            BASE_IMG=romancin/tinymediamanager:v4-latest
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tinymediamanager-amd:latest
